### ISSUE TITLE
OWASP NodeGoat Docker Image

### ISSUE THREAD

**Issue by binarymist** [carpedm20/awesome-hacking#21]
https://github.com/owasp/nodegoat has a [docker image](https://github.com/owasp/nodegoat#option-3---run-nodegoat-on-docker) which I've done quite a bit of work on and works well, may be worth adding. Let me know if you would rather have a PR?

Here is the [wiki](https://github.com/binarymist/NodeGoat/wiki/Security-Regression-Testing-with-Zap-API) around security regression testing for NodeGoat <-> ZAP that has a video teaser also.

**Comment by carpedm20** [comment]
Sure. Feel free to give me a PR.
