### ISSUE TITLE
broken link or repo

### ISSUE THREAD

**Issue by 0000x0** [carpedm20/awesome-hacking#37]
docker pull pandrew/metasploit
Using default tag: latest
Error response from daemon: repository pandrew/metasploit not found: does not exist or no pull access

**Comment by 0000x0** [comment]
one more 

Using default tag: latest
Error response from daemon: repository usertaken/archlinux-pentest-lxde not found: does not exist or no pull access

**Comment by n0ncetonic** [comment]
I've submitted a pull request to fix the docker link for Docker Metasploit to point to the official image (https://hub.docker.com/r/metasploitframework/metasploit-framework/).

I've also submitted a second pull request that recreated the usertaken/archlinux-pentest-lxde image which is now missing from DockerHub for some reason. You can find this docker image at https://hub.docker.com/r/noncetonic/archlinux-pentest-lxde

**Comment by n0ncetonic** [comment]
Heads up @0000x0 the PR I submitted for the metasploit docker image has now been merged and the doc reflects the new docker image. Still waiting on the Arch Linux Penetration Tester PR to get merged though

**Comment by deveyNull** [comment]
Seriously great work.
