### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by hksanduo** [carpedm20/awesome-hacking#43]
some docker connections are failed

**Comment by hksanduo** [comment]
docker-metasploit,Arch Linux Penetration Tester

**Comment by n0ncetonic** [comment]
I've addressed both of these issues on #37 and submitted the appropriate pull requests to this repo

**Comment by n0ncetonic** [comment]
Heads up @hksanduo my PR to fix the docker-metasploit thing just get accepted so it should work now if this is still an issue for you. Arch Linux Penetration Tester pull request is still open but you can also get the docker image from my pull request if you want

**Comment by chinnu1102** [comment]
> some docker connections are failed

Fixed
